### ISSUE TITLE
As a skeptical GUI user, I can create compound commands

### ISSUE THREAD

**Issue by JingYenLoh** [AY2021S1-CS2103-T16-3/tp#40]
... e.g. to view bills and pay them at the same time, so that I can perform common sequences of actions more quickly.

**Comment by JingYenLoh** [comment]
@AY2021S1-CS2103-T16-3/developers , @mkeoliya and I had a long discussion on how this value adds to our users. We weren't really able to find a concrete use case for this feature. Can anyone think of why this would be useful for our target users? We're leaning towards lowering the priority of (or even scrapping altogether) this User Story.

OTOH, we further refined our concept of the export feature, which we're documenting in #52 .

**Comment by Lysire** [comment]
I think creating new commands will add unnecessary complexity to the system. It will take a lot of effort to set up even if we only provide for a small number of commands in the compound command. Even then, it will not provide much value since it will not take a lot of time to type a small number of commands, especially if aliasing is done well.
